// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAseP_9uDmXWz4W6XFAasoktqytofB4vYY',
    appId: '1:82183177978:web:630203d98dc3e9b3c26b43',
    messagingSenderId: '82183177978',
    projectId: 'meal-a9115',
    authDomain: 'meal-a9115.firebaseapp.com',
    storageBucket: 'meal-a9115.firebasestorage.app',
    measurementId: 'G-6YB26N0TZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHI5cZ3ZZIYO_VktKQKgBVgIadMYJXGRo',
    appId: '1:82183177978:android:24973a24bd97d288c26b43',
    messagingSenderId: '82183177978',
    projectId: 'meal-a9115',
    storageBucket: 'meal-a9115.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYeL_VRk2UvSkypHfgTPLKcyewYHv8Sw8',
    appId: '1:82183177978:ios:8de6fc2696d44c5bc26b43',
    messagingSenderId: '82183177978',
    projectId: 'meal-a9115',
    storageBucket: 'meal-a9115.firebasestorage.app',
    iosBundleId: 'com.example.mealPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYeL_VRk2UvSkypHfgTPLKcyewYHv8Sw8',
    appId: '1:82183177978:ios:8de6fc2696d44c5bc26b43',
    messagingSenderId: '82183177978',
    projectId: 'meal-a9115',
    storageBucket: 'meal-a9115.firebasestorage.app',
    iosBundleId: 'com.example.mealPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAseP_9uDmXWz4W6XFAasoktqytofB4vYY',
    appId: '1:82183177978:web:0c521474b04324a1c26b43',
    messagingSenderId: '82183177978',
    projectId: 'meal-a9115',
    authDomain: 'meal-a9115.firebaseapp.com',
    storageBucket: 'meal-a9115.firebasestorage.app',
    measurementId: 'G-GEPV2PHKSR',
  );
}
